### ISSUE TITLE
OSX min version of conda-forge Python ahead of supported Anaconda min version

### ISSUE THREAD

**Issue by Lnaden** [conda-forge/python-feedstock#137]
The minimum OSX version of software that can be built on the `conda-forge` channel's version of python is 10.9, but the minimum version of OSX supported from the `default`/anaconda channel's python is 10.7. This has caused a problem with [a package](https://github.com/omnia-md/conda-dev-recipes/pull/86) where we are trying to slowly migrate to `conda-forge`, but now can no longer support the older OSX versions.

Having `conda-forge` be ahead of the `default` channel is fine, but because this is the fundamental `python` package we are talking about, I feel that there should be minimal to no differences between the channels which can cause unexpected behavior like this. We are looking at increasing the minimum OSX version of the package I am seeing the problem on, but I still wish to discuss the posiblity of re-aligning the minimum versions.

My guess is that Travis' Xcode6.4 only supports 10.9 at the earliest so that is causing the `python` built here to only build packages on that version or later. If this is not really feasible or possible, that is fine too, but it should probably be pointed out that there is a difference.

**Comment by jakirkham** [comment]
> The minimum OSX version of software that can be built on the `conda-forge` channel's version of python is 10.9

This is true.

> ...the minimum version of OSX supported from the `default`/anaconda channel's python is 10.7.

This use to be the case. However as noted back in this [blog post]( https://www.continuum.io/blog/developer-blog/anaconda-43-released ), Continuum now only supports macOS 10.9 and up.

> We are looking at increasing the minimum OSX version of the package I am seeing the problem on, but I still wish to discuss the posiblity of re-aligning the minimum versions.

As Continuum caught up with us, we are aligned.

> My guess is that Travis' Xcode6.4 only supports 10.9 at the earliest so that is causing the `python` built here to only build packages on that version or later.

Indeed. We are really at Travis CI's mercy here. In fact, we are very lucky that we have been able to keep 10.9 as we are actually building on a 10.10 image and specifying the target be 10.9, which took a fair bit of time to get right. There is no older SDK available in XCode 6.4. There has been occasional discussion about installing older SDKs into the XCode available. Some have done this with some success. However it may not be allowed with Apple's license agreement. So that could be a sticky area for conda-forge.

> If this is not really feasible or possible, that is fine too, but it should probably be pointed out that there is a difference.

As noted above, it's not. We are doing our best to build on the lowest version available. As we match with Continuum, I don't see any reason for us to switch to an older macOS that Continuum has dropped support for. Would welcome an addition to the docs on the webpage repo.
