### ISSUE TITLE
Document what you're doing to make Python so fast

### ISSUE THREAD

**Issue by itamarst** [conda-forge/python-feedstock#447]
I benchmarked a number of different Python builds (https://pythonspeed.com/articles/faster-python/), and Conda-Forge was the fastest. Anaconda was _not_, it was slower than Ubuntu 20.04 which is still slower than what you're doing.

If you have any sense of how (comparison to Anaconda's Python might be useful?), it would be great if it was written down somewhere so (A) this doesn't regress and (B) other Python maintainers can reproduce these results.

Thanks for all your work!

**Comment by mariusvniekerk** [comment]
We're doing pretty much the same pgo stuff that anaconda is doing and in fact our build recipes are nearly identical at this point.

My best guess is that we use a slightly newer set of compilers and dependencies.

**Comment by itamarst** [comment]
Unfortunately that suggests there are decent odds the performance improvement will just... disappear some day :( Thanks for the details.

**Comment by mingwandroid** [comment]
> Anaconda was not, it was slower than Ubuntu 20.04 which is still slower than what you're doing.

I would be love to see your testing methodology. It seems you tested only Linux and only a few tests? While I'm very pleased to hear conda-forge's builds are fastest in these tests, I believe, due to the lack of PGO in use on the conda-forge Windows builds (because we haven't been able to get it to work on CI yet), your results there would be different.

The optimizations in our python recipe (feel free to study what we do!) were largely inspired by the Debian recipe as maintained by Matthias Klose, including PGO and static linking as recommended to me by @pitrou. So that our performance is close to theirs is not surprising.

> Unfortunately that suggests there are decent odds the performance improvement will just... disappear some day :( Thanks for the details.

I disagree with this. We continue to look out for opportunities to accelerate our Python intepreter (along with the rest of it!) and this is an on-going effort. The [latest commit from me](https://github.com/conda-forge/python-feedstock/pull/448/commits/33bc6984bc4338187c84cb6cb5e9903af89229eb) in this direction comes thanks to a recommendation from @nehaljwani. In general so long as enough contributors care about performance things will only continue to get better. We continue to trim our packages and their dependencies and we (well, in particular @isuruf) invest a lot of time maintaining recent compilers to ensure we have access to the latest performance tweaks and options, and not just for Python itself, but also for its dependencies and the other software ecosystems we support.

If you happen across any interesting discussions or have ideas about performance tweaks for Python then we'd happily receive them! I have some on the back burner.

**Comment by itamarst** [comment]
I only care about Linux, personally, so only tested that. I used `pystone.py` initially, then switched to running some of the benchmarks in https://github.com/python/pyperformance (see the article for which ones).

Not saying you aren't investing in performance, you clearly are and you clearly are succeeding, and I appreciate all those efforts! More that... if there isn't a clear understanding of _what_ made something faster (or, better yet, a benchmark suite that runs every time) it's easy to regress when e.g. gcc tweaks their compiler passes slightly or something.

**Comment by mingwandroid** [comment]
Yeah we should get something into the builds to keep track of preformance. Maybe conda-build could help out.

I just run pyperformance manually every so often to make sure we're still on track. I can and do compare with older builds. Cheers!

**Comment by jakirkham** [comment]
The main thing from a performance standpoint as others have already said is PGO. Keeping reasonably recent compilers also helps. Since it seems understanding this performance delta is of interest to you, would suggest trying to build the recipe with different compiler versions and/or PGO off to get a sense of how these factor in.

If we wanted to start tracking this between builds (to catch regressions or measure performance improvements), setting up Airspeed Velocity on a dedicated machine would be helpful. Is this something you might be interested in/willing to lend resources towards? 🙂

**Comment by mingwandroid** [comment]
There is a clear understanding yes. I mean the contributors to this recipe understand python and C and the CPython code base as well as software construction in general. Changes are considered carefully. Ones affecting performance are checked in that direction and upstream discussions followed. As you can see from the commit message above sometimes i remember to leave some data behind and it also shows that some things get better and some worse for a given optimisation sometimes.

**Comment by itamarst** [comment]
It's possible that the approach I describe here: https://pythonspeed.com/articles/consistent-benchmarking-in-ci/ would allow doing benchmarks without requiring a dedicated machine. It's... not perfect, but it can catch meaningful regressions, and it's a lot simpler to setup.

Here's a quick experiment, with Python 3.8 and pystone.py, and using script from https://github.com/pythonspeed/cachegrind-benchmarking):

| Python | pystones, higher is better | Cachegrind (unified), lower is better |
|-----------|--------------|---------------------------------|
| Fedora 33 | ~200K/sec | 3727M |
| Conda-Forge | ~240K/sec | 2859M |

The measured performance improvements are 1.2× and 1.3×, depending which measure you use. So they're correlated, but definitely not identical. But correlated may be enough (or better than nothing).

**Comment by mingwandroid** [comment]
Does anyone have any experience with https://github.com/emeryberger/scalene ?

It piqued my interest when I saw it the other day. I might look into this some more ..

**Comment by jakirkham** [comment]
No though I've also seen this recently as well

More generally whether using a dedicated machine or some cloud instance to do detailed profiling, I think the point is this probably doesn't make sense to have this in conda-forge's CI. We've said similar things about measuring code coverage of packages for example. That said, this work is still valuable and I think we would be interested in working with you, we would just need to find a home for it

**Comment by mingwandroid** [comment]
My proposal, to get things moving for now, would be to add a new split package, conda-python-benchmarking which would depend on the various testing benchmark backends we can build out and support. Then we think about what to do with that afterwards.

**Comment by itamarst** [comment]
Part of the idea of using Cachegrind is that you _can_ in theory use CI, it will give pretty reproducible results across multiple runs. Will be pretty slow CI, of course.

**Comment by pitrou** [comment]
A couple of thoughts below:

* You should test on more benchmarks, not only 3 of them. One build may be faster than another one on a specific benchmark by pure luck. Ideally, run the entire [pyperformance](https://github.com/python/pyperformance) suite, which has a diverse set of benchmarks.

* pystones is really a pointless micro-benchmark, I don't think it's worth trying to measure it.

* Measuring the number of CPU instruction with CacheGrind won't necessarily tell you much about actual performance. The execution of code inside modern CPUs is quite complicated, and how fast those instructions are executed can vary a great deal due to various factors (such as cache / memory access patterns, the efficiency of branch prediction, or data dependencies between neighbouring instructions).

* When I worked at Anaconda (then Continuum), I had investigated the performance of Python builds and came to the conclusion that three factors were important: 1) a static build (i.e. no linking to a `libpython.so`), 2) profiling code execution on a decent workload (part of Python's own test suite gave good results), 3) using LTO + PGO to exploit the results of profiling.

The latter is what both Anaconda and Ubuntu builds do, AFAIK. Perhaps Anaconda builds with an older compiler and gets worse performance. But really, three benchmarks isn't enough.

**Comment by itamarst** [comment]
Here's (almost all of) pyperformance for conda-forge vs. anaconda; the former is faster across almost every benchmark, matching the 3 benchmarks I did.

Which suggests a question: if `pyperformance` really is a good representative workload, since it's real 3rd party application code, is it part of the PGO inputs?

```
CONDA-FORGE                                  ANACONDA

### 2to3 ###                                 ### 2to3 ###
Mean +- std dev: 409 ms +- 4 ms              Mean +- std dev: 447 ms +- 4 ms

### chameleon ###                            ### chameleon ###
Mean +- std dev: 11.8 ms +- 0.1 ms           Mean +- std dev: 12.7 ms +- 0.1 ms

### chaos ###                                ### chaos ###
Mean +- std dev: 139 ms +- 0 ms              Mean +- std dev: 159 ms +- 1 ms

### crypto_pyaes ###                         ### crypto_pyaes ###
Mean +- std dev: 137 ms +- 1 ms              Mean +- std dev: 163 ms +- 1 ms

### deltablue ###                            ### deltablue ###
Mean +- std dev: 9.22 ms +- 0.16 ms          Mean +- std dev: 11.1 ms +- 0.2 ms

### django_template ###                      ### django_template ###
Mean +- std dev: 63.0 ms +- 0.9 ms           Mean +- std dev: 72.2 ms +- 0.6 ms

### dulwich_log ###                          ### dulwich_log ###
Mean +- std dev: 86.6 ms +- 0.9 ms           Mean +- std dev: 93.3 ms +- 0.8 ms

### fannkuch ###                             ### fannkuch ###
Mean +- std dev: 606 ms +- 3 ms              Mean +- std dev: 683 ms +- 3 ms

### float ###                                ### float ###
Mean +- std dev: 156 ms +- 1 ms              Mean +- std dev: 178 ms +- 1 ms

### genshi_text ###                          ### genshi_text ###
Mean +- std dev: 38.2 ms +- 0.3 ms           Mean +- std dev: 40.4 ms +- 0.3 ms

### genshi_xml ###                           ### genshi_xml ###
Mean +- std dev: 81.0 ms +- 1.2 ms           Mean +- std dev: 84.9 ms +- 0.8 ms

### go ###                                   ### go ###
Mean +- std dev: 310 ms +- 3 ms              Mean +- std dev: 364 ms +- 5 ms

### hexiom ###                               ### hexiom ###
Mean +- std dev: 11.8 ms +- 0.0 ms           Mean +- std dev: 13.8 ms +- 0.0 ms

### json_dumps ###                           ### json_dumps ###
Mean +- std dev: 15.4 ms +- 0.1 ms           Mean +- std dev: 16.7 ms +- 0.1 ms

### json_loads ###                           ### json_loads ###
Mean +- std dev: 30.8 us +- 0.2 us           Mean +- std dev: 34.3 us +- 0.3 us

### logging_format ###                       ### logging_format ###
Mean +- std dev: 11.5 us +- 0.2 us           Mean +- std dev: 13.1 us +- 0.2 us

### logging_silent ###                       ### logging_silent ###
Mean +- std dev: 252 ns +- 4 ns              Mean +- std dev: 287 ns +- 3 ns

### logging_simple ###                       ### logging_simple ###
Mean +- std dev: 10.6 us +- 0.2 us           Mean +- std dev: 11.9 us +- 0.2 us

### mako ###                                 ### mako ###
Mean +- std dev: 20.0 ms +- 0.1 ms           Mean +- std dev: 22.1 ms +- 0.1 ms

### meteor_contest ###                       ### meteor_contest ###
Mean +- std dev: 129 ms +- 4 ms              Mean +- std dev: 138 ms +- 4 ms

### nbody ###                                ### nbody ###
Mean +- std dev: 164 ms +- 1 ms              Mean +- std dev: 195 ms +- 0 ms

### nqueens ###                              ### nqueens ###
Mean +- std dev: 119 ms +- 1 ms              Mean +- std dev: 138 ms +- 1 ms

### pathlib ###                              ### pathlib ###
Mean +- std dev: 22.1 ms +- 0.3 ms           Mean +- std dev: 24.0 ms +- 0.4 ms

### pickle ###                               ### pickle ###
Mean +- std dev: 12.6 us +- 0.2 us           Mean +- std dev: 11.2 us +- 0.1 us

### pickle_dict ###                          ### pickle_dict ###
Mean +- std dev: 29.6 us +- 0.1 us           Mean +- std dev: 32.9 us +- 0.1 us

### pickle_list ###                          ### pickle_list ###
Mean +- std dev: 4.72 us +- 0.10 us          Mean +- std dev: 4.79 us +- 0.03 us

### pickle_pure_python ###                   ### pickle_pure_python ###
Mean +- std dev: 571 us +- 3 us              Mean +- std dev: 654 us +- 6 us

### pidigits ###                             ### pidigits ###
Mean +- std dev: 218 ms +- 0 ms              Mean +- std dev: 239 ms +- 7 ms

### pyflate ###                              ### pyflate ###
Mean +- std dev: 862 ms +- 7 ms              Mean +- std dev: 1.00 sec +- 0.02 sec

### python_startup ###                       ### python_startup ###
Mean +- std dev: 10.6 ms +- 0.0 ms           Mean +- std dev: 10.9 ms +- 0.0 ms

### python_startup_no_site ###               ### python_startup_no_site ###
Mean +- std dev: 7.09 ms +- 0.04 ms          Mean +- std dev: 7.27 ms +- 0.04 ms

### raytrace ###                             ### raytrace ###
Mean +- std dev: 607 ms +- 3 ms              Mean +- std dev: 724 ms +- 10 ms

### regex_compile ###                        ### regex_compile ###
Mean +- std dev: 217 ms +- 5 ms              Mean +- std dev: 248 ms +- 6 ms

### regex_dna ###                            ### regex_dna ###
Mean +- std dev: 238 ms +- 2 ms              Mean +- std dev: 235 ms +- 0 ms

### regex_effbot ###                         ### regex_effbot ###
Mean +- std dev: 3.62 ms +- 0.00 ms          Mean +- std dev: 3.67 ms +- 0.07 ms

### regex_v8 ###                             ### regex_v8 ###
Mean +- std dev: 28.3 ms +- 0.0 ms           Mean +- std dev: 31.5 ms +- 0.2 ms

### richards ###                             ### richards ###
Mean +- std dev: 86.0 ms +- 1.3 ms           Mean +- std dev: 103 ms +- 1 ms

### scimark_fft ###                          ### scimark_fft ###
Mean +- std dev: 462 ms +- 1 ms              Mean +- std dev: 521 ms +- 1 ms

### scimark_lu ###                           ### scimark_lu ###
Mean +- std dev: 195 ms +- 3 ms              Mean +- std dev: 234 ms +- 2 ms

### scimark_monte_carlo ###                  ### scimark_monte_carlo ###
Mean +- std dev: 135 ms +- 1 ms              Mean +- std dev: 153 ms +- 1 ms

### scimark_sor ###                          ### scimark_sor ###
Mean +- std dev: 256 ms +- 3 ms              Mean +- std dev: 289 ms +- 5 ms

### scimark_sparse_mat_mult ###              ### scimark_sparse_mat_mult ###
Mean +- std dev: 5.61 ms +- 0.01 ms          Mean +- std dev: 6.83 ms +- 0.02 ms

### spectral_norm ###                        ### spectral_norm ###
Mean +- std dev: 179 ms +- 0 ms              Mean +- std dev: 200 ms +- 2 ms

### sqlalchemy_declarative ###               ### sqlalchemy_declarative ###
Mean +- std dev: 208 ms +- 3 ms              Mean +- std dev: 221 ms +- 3 ms

### sqlalchemy_imperative ###                ### sqlalchemy_imperative ###
Mean +- std dev: 39.7 ms +- 1.0 ms           Mean +- std dev: 41.1 ms +- 0.6 ms

### sqlite_synth ###                         ### sqlite_synth ###
Mean +- std dev: 3.32 us +- 0.02 us          Mean +- std dev: 3.69 us +- 0.03 us

### sympy_expand ###                         ### sympy_expand ###
Mean +- std dev: 620 ms +- 5 ms              Mean +- std dev: 678 ms +- 8 ms

### sympy_integrate ###                      ### sympy_integrate ###
Mean +- std dev: 31.1 ms +- 0.3 ms           Mean +- std dev: 33.5 ms +- 0.2 ms

### sympy_sum ###                            ### sympy_sum ###
Mean +- std dev: 275 ms +- 2 ms              Mean +- std dev: 292 ms +- 3 ms

### sympy_str ###                            ### sympy_str ###
Mean +- std dev: 421 ms +- 11 ms             Mean +- std dev: 455 ms +- 8 ms

### telco ###                                ### telco ###
Mean +- std dev: 8.05 ms +- 0.03 ms          Mean +- std dev: 8.40 ms +- 0.04 ms

### tornado_http ###                         ### tornado_http ###
Mean +- std dev: 211 ms +- 3 ms              Mean +- std dev: 221 ms +- 2 ms

### unpack_sequence ###                      ### unpack_sequence ###
Mean +- std dev: 71.0 ns +- 2.0 ns           Mean +- std dev: 71.3 ns +- 0.5 ns

### unpickle ###                             ### unpickle ###
Mean +- std dev: 16.1 us +- 0.5 us           Mean +- std dev: 18.7 us +- 1.7 us

### unpickle_list ###                        ### unpickle_list ###
Mean +- std dev: 5.57 us +- 0.02 us          Mean +- std dev: 5.43 us +- 0.03 us

### unpickle_pure_python ###                 ### unpickle_pure_python ###
Mean +- std dev: 393 us +- 2 us              Mean +- std dev: 463 us +- 6 us

### xml_etree_parse ###                      ### xml_etree_parse ###
Mean +- std dev: 186 ms +- 2 ms              Mean +- std dev: 187 ms +- 3 ms
```

**Comment by pitrou** [comment]
Thanks for the numbers. Interesting that conda-forge is significantly faster on most benchmarks.

I can't tell whether `pyperformance` is really representative. But it's simply a better set of benchmarks than pystones ;-)
For PGO, you want to avoid situations where some code paths are not exercised, and the Python test suite is a good way of avoiding such situations. You can of course add other workloads into the mix. But the more workloads you run under PGO, the slower the build phase :-)

**Comment by mingwandroid** [comment]
> Unfortunately that suggests there are decent odds the performance improvement will just... disappear some day :(

.. relative to the Python in Anaconda Distribution the conda-forge performance improvement may well disappear (as soon as we update our compilers).

.. but, since the recipes are shared between both efforts, and while I continue to work on them both, I will remain in competition with myself for the fastest Python interpreter around between AD and CF (and MSYS2/mingw-w64). I would love to get PGO working on conda-forge's Windows Python packages.

**Comment by itamarst** [comment]
When the performance improvement in Anaconda improves, e.g. due to compiler improvement, could you write that up? Because then they'll be clear "if you upgrade to GCC X.Y you will get an improvement" evidence.

**Comment by mingwandroid** [comment]
Definitely!
