### ISSUE TITLE
Windows runtimes missing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#47]
Seems that Windows runtimes are not being pulled in by Python 3.5 or 3.4 AFAICT. Please see these [builds]( https://ci.appveyor.com/project/conda-forge/pyzmq-feedstock/build/1.0.12 ) for reference. Should these be added as build and run dependencies? It's possible I'm missing something as I'm not a Windows expert. So, please don't hesitate to correct me.

cc @msarahan @jjhelmus

**Comment by pelson** [comment]
Agreed. We should be pulling in the appropriate msvc_runtime.

https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-3.5/meta.yaml#L40

**Comment by jjhelmus** [comment]
I can replicate this issue locally, `msvc_runtime` should be a run (and build?) requirement for python on Windows, will submit a fix shortly.

**Comment by msarahan** [comment]
I don't think you want msvc_runtime.  Instead, you want the appropriate vs20??_runtime.  The difference is that msvc_runtime does not allow side-by-side install of multiple msvc runtimes.  Though mixing runtimes in a single process is not advisable, we should not prevent having multiple runtimes in one environment, because people can run different programs that use different runtimes.
