### ISSUE TITLE
Python 3.13t sitecustomize.py workaround is ineffective when a system-wide sitecustomize.py is present.

### ISSUE THREAD

**Issue by cbouss** [conda-forge/python-feedstock#730]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Python 3.13t sitecustomize.py workaround is ineffective when a system-wide sitecustomize.py is present.

The workaround for https://github.com/conda/conda/issues/14053 is to add site directory `lib/python3.13/site-packages/`. See https://github.com/conda-forge/python-feedstock/commit/bdc3eebd6de855efc104feb181ba61430e5133ea#diff-a6a19a192f8fe15a32c4a1d019dfbba33a7128027489cc91a25f95a90b16d92eR4

On machines where a system-wide sitecutstomize.py is available, the system-wide version takes precedence over the one of the workaround.

Instead, the functionality of sitecustomize.py could be put into a .pth file.

### Installed packages

python 3.13 cp313t

### Environment info

python 3.13 cp313t

**Comment by isuruf** [comment]
Can you give a reproducer? Also, isn't that an abuse of using `sitecustomize.py`? A user should use `usercustomize.py` not `sitecustomize.py`.

**Comment by antocuni** [comment]
I confirm that I experience the bug on my system.
My setup is the following:
- I have a `~/env/pypath` directory in my home which contains a [sitecustomize.py]( https://github.com/antocuni/env/blob/master/pypath/sitecustomize.py)
- I have a [PYTHONPATH](https://github.com/antocuni/env/blob/master/dotfiles/bash_profile#L47) env variable which allows to automatically load it in any python/virtualenv combination

This setup has worked flawlessly since ~2006, across multiple python versions and all possible ways of installing python (`apt-get`, `make && make install`, conda, uv, pypy tarballs, etc). If I recall correctly I started to use it with python 2.3 or so.

I agree that `usercustomize.py` is probably a better option, but it was introduced "only" in 2.6 :)
I'm also pretty sure that I learnt the PYTHONPATH/sitecustomize trick by someone else, so I suspect I'm not the only one in this situation.

**Comment by isuruf** [comment]
Using a `.pth` file now.
